"""v2: process generated images (crop / resize / depth) and pack them into assets/images.js.

usage: python pack_images.py [--depth-only] [--depth-model /tmp/depth/q.onnx]
  depth maps (Depth-Anything-V2 small, ONNX) are cached in ../gen/depth/<name>.png  (white = near)
  output: ../../assets/images.js  ->  window.OLK_IMG = { name: {src, w, h}, ... }
"""
import base64, io, json, os, sys, time
import numpy as np
from PIL import Image, ImageFilter

HERE = os.path.dirname(os.path.abspath(__file__))
RAW = os.path.join(HERE, '..', 'gen', 'raw')
DEP = os.path.join(HERE, '..', 'gen', 'depth')
OUT = os.path.join(HERE, '..', '..', 'assets', 'images.js')

# 16:9 plates with a depth map (parallax / relief)
WIDE = ['paris_red', 'paris_blue', 'louvre', 'eva01_cage', 'eva01_eye', 'nti', 'village', 'rei_paddy', 'rei_dusk',
        'wunder', 'fleet', 'lilith', 'shinji_cam', 'set_fight', 'asuka_beach', 'gendo_train', 'kaworu', 'fire_fight',
        'misato_last', 'red_crosses', 'rei_white', 'gendo_yui', 'shinji_red', 'shinji_blue', 'ube_platform',
        'ube_pilots', 'ube_air', 'p_town', 'lance', 'ube_bench', 'at_clash']
# 16:9 montage cards (fast cuts, no depth needed)
CARDS = ['m_misato', 'm_asuka', 'm_mari', 'm_guns', 'm_swarm', 'm_u02', 'genga', 'm_ritsuko', 'm_toji', 'm_kensuke', 'm_sakura']
SQUARE = {'snap1': 768, 'snap2': 768, 'snap3': 768, 'snap4': 768, 'gallery': 1024}
CUTS = {'cut_e00': 1024, 'cut_e01': 1024, 'cut_e02': 1024, 'cut_e08': 1024, 'cut_e13': 1024, 'u08_desc': 1024,
        'u08_cut': 720, 'p_run': 720, 'cut_shinji_seat': 1024, 'cut_gendo_seat': 1024}


def load(n):
    for e in ('png', 'jpg', 'webp'):
        p = os.path.join(RAW, f'{n}.{e}')
        if os.path.exists(p): return Image.open(p)
    raise FileNotFoundError(n)


def depth_map(sess, im):
    """relative depth, 0 = far .. 1 = near, same size as im"""
    W, H = im.size
    h = 518; w = int(round(W / H * h / 14)) * 14
    x = np.asarray(im.convert('RGB').resize((w, h), Image.BICUBIC), np.float32) / 255
    x = (x - [0.485, 0.456, 0.406]) / [0.229, 0.224, 0.225]
    d = sess.run(None, {'pixel_values': x.transpose(2, 0, 1)[None].astype(np.float32)})[0][0]
    lo, hi = np.percentile(d, 1), np.percentile(d, 99.5)
    d = np.clip((d - lo) / (hi - lo + 1e-6), 0, 1)
    return Image.fromarray((d * 255).astype(np.uint8)).resize((W, H), Image.BICUBIC)


def uri(im, fmt='webp', q=84):
    b = io.BytesIO()
    if fmt == 'webp': im.save(b, 'WEBP', quality=q, method=4)
    else: im.save(b, 'PNG', optimize=True)
    return f'data:image/{fmt};base64,' + base64.b64encode(b.getvalue()).decode()


def depths(model, budget=160):
    os.makedirs(DEP, exist_ok=True)
    t0 = time.time(); sess = None
    for n in WIDE:
        p = os.path.join(DEP, f'{n}.png')
        if os.path.exists(p): continue
        if time.time() - t0 > budget: print('budget reached'); return False
        if sess is None:
            import onnxruntime as ort
            sess = ort.InferenceSession(model, providers=['CPUExecutionProvider'])
        depth_map(sess, load(n)).save(p)
        print('depth', n, f'{time.time() - t0:.0f}s', flush=True)
    return True


def main():
    model = sys.argv[sys.argv.index('--depth-model') + 1] if '--depth-model' in sys.argv else '/tmp/depth/q.onnx'
    if not depths(model) or '--depth-only' in sys.argv: return
    out, sizes = {}, {}

    def put(name, im, **kw):
        s = uri(im, **kw); out[name] = {'src': s, 'w': im.width, 'h': im.height}; sizes[name] = len(s) // 1024

    for n in WIDE:
        put(n, load(n).convert('RGB').resize((1600, 900), Image.LANCZOS), q=82)
        d = Image.open(os.path.join(DEP, f'{n}.png')).convert('L')
        put(n + '_d', d.resize((800, 450), Image.LANCZOS).filter(ImageFilter.GaussianBlur(1.2)), q=88)
    for n in CARDS:
        put(n, load(n).convert('RGB').resize((1280, 720), Image.LANCZOS), q=80)
    for n, s in SQUARE.items():
        put(n, load(n).convert('RGB').resize((s, s), Image.LANCZOS), q=84)
    im = load('yui_lisa').convert('RGB')
    put('yui_lisa', im.resize((int(im.width * 1024 / im.height), 1024), Image.LANCZOS), q=86)
    put('earth_tex', load('earth_tex').convert('RGB').resize((2048, 1024), Image.LANCZOS), q=86)
    for n, h in CUTS.items():  # tight alpha crop, fixed height
        im = load(n).convert('RGBA'); a = np.asarray(im)[..., 3]
        ys, xs = np.where(a > 8); pad = 12
        im = im.crop((max(xs.min() - pad, 0), max(ys.min() - pad, 0), min(xs.max() + pad, im.width), min(ys.max() + pad, im.height)))
        im = im.resize((int(im.width * h / im.height), h), Image.LANCZOS)
        put(n, im, q=88)

    with open(OUT, 'w', encoding='utf-8') as f:
        f.write('/* generated by source/tools/pack_images.py */\nwindow.OLK_IMG=' + json.dumps(out, separators=(',', ':')) + ';\n')
    print(json.dumps(sizes), f'total {os.path.getsize(OUT) // 1024}KB')


if __name__ == '__main__':
    main()
