"""Process generated images (crop / resize / depth / atlas) and pack them into assets/images.js.

usage: python pack_images.py [--depth-model /tmp/depth/q.onnx]
  depth maps (Depth-Anything-V2 small, ONNX) are cached in ../gen/depth/<name>.png  (white = near)
  output: ../../assets/images.js  ->  window.OLK_IMG = { name: {src, w, h}, ... }
"""
import base64, io, json, os, sys
import numpy as np
from PIL import Image, ImageFilter

HERE = os.path.dirname(os.path.abspath(__file__))
RAW = os.path.join(HERE, '..', 'gen', 'raw')
DEP = os.path.join(HERE, '..', 'gen', 'depth')
OUT = os.path.join(HERE, '..', '..', 'assets', 'images.js')

ATLAS = ['two', 'sea', 'room', 'pyramid', 'sky', 'road', 'bokeh', 'field', 'train', 'moon', 'lamp', 'white']  # == PHOTO order
WIDE = ['platform', 'redsea', 'trainwin', 'clouds', 'meadow', 'viewfinder']
DEPTH = WIDE + ['hero']
CUTS = ['cut_her', 'cut_her_back', 'cut_him']


def load(n):
    for e in ('png', 'jpg', 'webp'):
        p = os.path.join(RAW, f'{n}.{e}')
        if os.path.exists(p): return Image.open(p)
    raise FileNotFoundError(n)


def depth_map(sess, im):
    """relative depth, 0 = far .. 1 = near, same size as im"""
    W, H = im.size
    h = 518; w = int(round(W / H * h / 14)) * 14
    x = np.asarray(im.convert('RGB').resize((w, h), Image.BICUBIC), np.float32) / 255
    x = (x - [0.485, 0.456, 0.406]) / [0.229, 0.224, 0.225]
    d = sess.run(None, {'pixel_values': x.transpose(2, 0, 1)[None].astype(np.float32)})[0][0]
    lo, hi = np.percentile(d, 1), np.percentile(d, 99.5)
    d = np.clip((d - lo) / (hi - lo + 1e-6), 0, 1)
    return Image.fromarray((d * 255).astype(np.uint8)).resize((W, H), Image.BICUBIC)


def uri(im, fmt='webp', q=84):
    b = io.BytesIO()
    if fmt == 'webp': im.save(b, 'WEBP', quality=q, method=6)
    else: im.save(b, 'PNG', optimize=True)
    return f'data:image/{fmt};base64,' + base64.b64encode(b.getvalue()).decode()


def main():
    os.makedirs(DEP, exist_ok=True)
    model = sys.argv[sys.argv.index('--depth-model') + 1] if '--depth-model' in sys.argv else '/tmp/depth/q.onnx'
    sess = None
    out, sizes = {}, {}

    def put(name, im, **kw):
        s = uri(im, **kw); out[name] = {'src': s, 'w': im.width, 'h': im.height}; sizes[name] = len(s) // 1024

    # 4x3 memory atlas, 512px cells
    C = 512; at = Image.new('RGB', (C * 4, C * 3))
    for i, n in enumerate(ATLAS):
        at.paste(load(n).convert('RGB').resize((C, C), Image.LANCZOS), ((i % 4) * C, (i // 4) * C))
    put('atlas', at, q=82)
    put('hero', load('hero').convert('RGB').resize((1024, 1024), Image.LANCZOS), q=88)

    for n in WIDE:
        put(n, load(n).convert('RGB').resize((1600, 900), Image.LANCZOS), q=84)

    for n in DEPTH:
        p = os.path.join(DEP, f'{n}.png')
        if not os.path.exists(p):
            if sess is None:
                import onnxruntime as ort
                sess = ort.InferenceSession(model, providers=['CPUExecutionProvider'])
            depth_map(sess, load(n)).save(p)
            print('depth', n, flush=True)
        d = Image.open(p).convert('L')
        d = d.resize((768, 768) if n == 'hero' else (800, 450), Image.LANCZOS).filter(ImageFilter.GaussianBlur(1.2))
        put(n + '_d', d, q=90)

    for n in CUTS:  # tight alpha crop, fixed height
        im = load(n).convert('RGBA'); a = np.asarray(im)[..., 3]
        ys, xs = np.where(a > 8); pad = 12
        im = im.crop((max(xs.min() - pad, 0), max(ys.min() - pad, 0), min(xs.max() + pad, im.width), min(ys.max() + pad, im.height)))
        im = im.resize((int(im.width * 900 / im.height), 900), Image.LANCZOS)
        put(n, im, q=88)

    im = load('run_her').convert('RGB'); g = np.asarray(im.convert('L'))  # pencil runner on white paper (multiply-blended)
    ys, xs = np.where(g < 235); pad = 16
    im = im.crop((max(xs.min() - pad, 0), max(ys.min() - pad, 0), min(xs.max() + pad, im.width), min(ys.max() + pad, im.height)))
    put('run_her', im.resize((int(im.width * 900 / im.height), 900), Image.LANCZOS), q=86)

    with open(OUT, 'w', encoding='utf-8') as f:
        f.write('/* generated by source/tools/pack_images.py */\nwindow.OLK_IMG=' + json.dumps(out, separators=(',', ':')) + ';\n')
    print(json.dumps(sizes), f'total {os.path.getsize(OUT) // 1024}KB')


if __name__ == '__main__':
    main()
