#!/usr/bin/env python3
"""Subset the MV fonts to the characters actually used and embed them as base64 woff2.
usage: build_fonts.py <src_dir> <out_css> [fontsource_dir]
Fonts (all SIL OFL): Shippori Mincho, Cormorant Garamond, Mrs Saint Delafield (fontsource packages),
Noto Serif CJK SC and Noto Sans Mono (system)."""
import sys, os, re, glob, io, base64
from fontTools import subset
from fontTools.ttLib import TTFont, TTCollection

SRC, OUT = sys.argv[1], sys.argv[2]
FD = sys.argv[3] if len(sys.argv) > 3 else '/tmp/fonts'
ASCII = {c for c in range(0x20, 0x7f)}
PUNCT = {ord(c) for c in '—–’‘“”…·「」『』、。，．！？：；（）《》〈〉　'}

texts = {f: open(f, encoding='utf-8').read() for f in glob.glob(os.path.join(SRC, '**/*.js'), recursive=True)}
ALL = {ord(c) for s in texts.values() for c in s if ord(c) >= 0x20}
lyr = next((s for f, s in texts.items() if f.endswith('lyrics-data.js')), '')
orig = set()
for m in re.finditer(r"\[\s*[\d.]+,\s*[\d.]+,\s*'((?:[^'\\]|\\.)*)'", lyr):
    orig |= {ord(c) for c in m.group(1)}
# Japanese translations of English lines (7th field) are set in Mincho too
for m in re.finditer(r"'((?:[^'\\]|\\.)*)'\],?\s*$", lyr, re.M):
    orig |= {ord(c) for c in m.group(1)}
kana = {c for c in ALL if 0x3040 <= c <= 0x30ff}
mincho_lines = {ord(c) for s in texts.values() for ln in s.splitlines() if 'FONTS.mincho' in ln for c in ln}
SETS = {
    'jp': ASCII | PUNCT | orig | kana | {c for c in mincho_lines if c > 0x2e80},
    'latin': ASCII | PUNCT,
    'cjk': ASCII | PUNCT | {c for c in ALL if c > 0x2000},
}

def sub(font, cps):
    o = subset.Options()
    o.flavor = 'woff2'; o.layout_features = ['*']; o.name_IDs = ['*']; o.notdef_outline = True; o.hinting = False
    s = subset.Subsetter(o); s.populate(unicodes=cps); s.subset(font)
    b = io.BytesIO(); subset.save_font(font, b, o)
    return b.getvalue()

def face(fam, w, st, data, cps=None):
    ur = ('unicode-range:' + ','.join('U+%X' % c for c in sorted(cps)) + ';') if cps else ''
    return "@font-face{font-family:'%s';font-style:%s;font-weight:%d;font-display:block;src:url(data:font/woff2;base64,%s) format('woff2');%s}\n" % (
        fam, st, w, base64.b64encode(data).decode(), ur)

def parse_ur(s):
    out = set()
    for p in s.split(','):
        p = p.strip().upper().replace('U+', '')
        if '-' in p:
            a, b = p.split('-'); out |= set(range(int(a, 16), int(b, 16) + 1))
        elif '?' in p:
            out |= set(range(int(p.replace('?', '0'), 16), int(p.replace('?', 'F'), 16) + 1))
        elif p:
            out.add(int(p, 16))
    return out

def fontsource(fam, w, st, css, want):
    txt = open(css, encoding='utf-8').read(); base = os.path.dirname(css); res = ''
    for blk in re.findall(r'@font-face\s*{([^}]*)}', txt):
        u = re.search(r"url\(([^)]+?\.woff2)\)", blk); r = re.search(r'unicode-range:\s*([^;]+);', blk)
        need = want & parse_ur(r.group(1)) if r else set(want)
        if not need:
            continue
        f = TTFont(os.path.join(base, u.group(1).strip('\'"')))
        cm = f.getBestCmap(); need = {c for c in need if c in cm}
        if need:
            res += face(fam, w, st, sub(f, need), need)
    return res

def system(fam, w, st, path, want, key=None):
    n = 0
    if path.lower().endswith('.ttc'):
        col = TTCollection(path)
        n = next(i for i, f in enumerate(col.fonts) if key in (f['name'].getDebugName(1) or ''))
    f = TTFont(path, fontNumber=n); cm = f.getBestCmap()
    return face(fam, w, st, sub(f, {c for c in want if c in cm}))

def find(name):
    hits = glob.glob('/usr/share/fonts/**/' + name, recursive=True)
    return hits[0] if hits else None

P = lambda pkg, css: os.path.join(FD, pkg, 'package', css)
SM, CG, MS = 'fontsource-shippori-mincho-5.3.0', 'fontsource-cormorant-garamond-5.3.0', 'fontsource-mrs-saint-delafield-5.3.0'
css = '/* generated by tools/build_fonts.py - subset fonts, SIL Open Font License */\n'
css += fontsource('OLK Mincho', 400, 'normal', P(SM, '400.css'), SETS['jp'])
css += fontsource('OLK Mincho', 500, 'normal', P(SM, '500.css'), SETS['jp'])
for w, st, f in [(300, 'italic', '300-italic.css'), (500, 'italic', '500-italic.css'), (400, 'normal', '400.css'), (500, 'normal', '500.css')]:
    css += fontsource('OLK Serif', w, st, P(CG, f), SETS['latin'])
css += fontsource('OLK Script', 400, 'normal', P(MS, '400.css'), SETS['latin'])
css += system('OLK SC', 400, 'normal', find('NotoSerifCJK-Regular.ttc'), SETS['cjk'], key='SC')
mono = find('NotoSansMono-Regular.ttf') or find('DejaVuSansMono.ttf')
if mono:
    css += system('OLK Mono', 400, 'normal', mono, SETS['latin'])
open(OUT, 'w', encoding='utf-8').write(css)
print('fonts.css %.0f KB | jp %d cjk %d glyph targets' % (len(css) / 1024, len(SETS['jp']), len(SETS['cjk'])))
