// Precomputed audio features (window.OLK_AUDIO, generated by tools/analyze_audio.py).
// Live WebAudio analysis is blocked on file://, so every reactive value is sampled from
// baked data as a pure function of time -> the MV is deterministic and fully seekable.
const D = window.OLK_AUDIO || null;

function decode(b64) {
  const bin = atob(b64);
  const out = new Float32Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i) / 255;
  return out;
}

export const FPS = D ? D.fps : 60;
export const PERIOD = D ? D.period : 60 / 111.995; // 112 BPM
export const BEAT0 = D ? D.beat0 : 0.095;
export const BAR0 = D ? D.bar0 : BEAT0 + 2 * PERIOD; // downbeat grid
export const BAR = PERIOD * 4;
export const DURATION = D ? D.duration : 252.03;

const ch = {};
const cum = {};
let spec = null;
if (D) {
  for (const k in D.ch) {
    const a = decode(D.ch[k]);
    const c = new Float32Array(a.length + 1);
    for (let i = 0; i < a.length; i++) c[i + 1] = c[i] + a[i] / FPS;
    ch[k] = a;
    cum[k] = c;
  }
  spec = decode(D.spec);
}
const EV = (D && D.ev) || {}, EVA = (D && D.evA) || {};

function sample(a, t, fps) {
  if (!a) return 0;
  const x = t * fps;
  const i = Math.floor(x);
  if (i < 0) return a[0];
  if (i >= a.length - 1) return a[a.length - 1];
  const f = x - i;
  return a[i] + (a[i + 1] - a[i]) * f;
}

export const audio = {
  ok: !!D,
  /** channel value 0..1: loud, low, mid, high, kick, snare, onset, energy */
  get(name, t) { return sample(ch[name], t, FPS); },
  /** integral of a channel over [0,t] - use for deterministic "accumulated" motion */
  integral(name, t) { return sample(cum[name], t, FPS); },
  /** 32-band log spectrum, band 0..31 */
  spectrum(band, t) {
    if (!spec) return 0;
    const B = D.specBands;
    const x = t * D.specFps;
    let i = Math.floor(x);
    const f = x - i;
    i = Math.max(0, Math.min(D.specN - 2, i));
    return spec[i * B + band] * (1 - f) + spec[(i + 1) * B + band] * f;
  },
  specRow(t, out) { for (let b = 0; b < 32; b++) out[b] = this.spectrum(b, t); return out; },
  beat(t) { return (t - BEAT0) / PERIOD; },
  bar(t) { return (t - BAR0) / BAR; },
  /** 1 on each beat decaying to 0 */
  beatPulse(t, sharp = 6) { const b = this.beat(t); return b < 0 ? 0 : Math.exp(-(b - Math.floor(b)) * sharp); },
  barPulse(t, sharp = 4) { const b = this.bar(t); return b < 0 ? 0 : Math.exp(-(b - Math.floor(b)) * sharp); },
  beatTime(n) { return BEAT0 + n * PERIOD; },
  barTime(n) { return BAR0 + n * BAR; },
  /** detected drum events: 'kick' | 'snare' | 'hat' | 'hit' (strong accents) */
  events(ev) { return EV[ev] || []; },
  /** index of the last event <= t (-1 if none) */
  last(ev, t) {
    const a = EV[ev]; if (!a || !a.length || a[0] > t) return -1;
    let lo = 0, hi = a.length - 1;
    while (lo < hi) { const m = (lo + hi + 1) >> 1; if (a[m] <= t) lo = m; else hi = m - 1; }
    return lo;
  },
  /** seconds since the last event (Infinity if none) */
  since(ev, t) { const i = this.last(ev, t); return i < 0 ? Infinity : t - EV[ev][i]; },
  /** amplitude (0..1) of the last event */
  amp(ev, t) { const i = this.last(ev, t); return i < 0 ? 0 : (EVA[ev] ? EVA[ev][i] : 1); },
  /** exp-decay pulse from the last event, scaled by its amplitude */
  hitPulse(ev, t, decay = 8) { const i = this.last(ev, t); if (i < 0) return 0; return (EVA[ev] ? EVA[ev][i] : 1) * Math.exp(-(t - EV[ev][i]) * decay); },
  /** number of events in [t0, t] -> deterministic step counters ("advance on every kick") */
  count(ev, t0, t) { return Math.max(0, this.last(ev, t) - this.last(ev, t0)); },
  /** next event time after t */
  next(ev, t) { const a = EV[ev], i = this.last(ev, t) + 1; return a && i < a.length ? a[i] : Infinity; },
};
