"""Pre-compute per-frame audio features for the web MV (file:// can't use live WebAudio analysis).
Output: build/audio-data.js  ->  window.OLK_AUDIO = {...}
Channels are quantised to uint8 and base64 encoded.  60 fps for envelopes, 30 fps for a 32-band spectrum."""
import numpy as np, librosa, json, base64, sys
SRC = sys.argv[1] if len(sys.argv) > 1 else '/tmp/work/mono24.wav'
OUT = sys.argv[2] if len(sys.argv) > 2 else '/tmp/olk/build/audio-data.js'
sr = 24000
y, _ = librosa.load(SRC, sr=sr, mono=True)
dur = len(y) / sr
hop = 400                                  # 60 fps
S = np.abs(librosa.stft(y, n_fft=2048, hop_length=hop)) ** 2
freqs = librosa.fft_frequencies(sr=sr, n_fft=2048)
n = S.shape[1]
fps = sr / hop

def band(lo, hi):
    m = (freqs >= lo) & (freqs < hi)
    return S[m].sum(0) + 1e-12

def norm_db(x, lo=3, hi=99.7, gamma=1.0):
    d = 10 * np.log10(x)
    a, b = np.percentile(d, lo), np.percentile(d, hi)
    return np.clip((d - a) / (b - a), 0, 1) ** gamma

def smooth(x, att, rel):
    """one-pole attack/release follower (seconds)"""
    ka, kr = np.exp(-1 / (att * fps)), np.exp(-1 / (rel * fps))
    out = np.zeros_like(x); v = 0.0
    for i, s in enumerate(x):
        k = ka if s > v else kr
        v = k * v + (1 - k) * s
        out[i] = v
    return out

def flux(x):
    lx = np.log(x)
    return np.maximum(0, np.diff(lx, prepend=lx[0]))

def pulses(fx, delta, wait, tau):
    fx = fx / (np.percentile(fx, 99.5) + 1e-9)
    pk = librosa.util.peak_pick(fx, pre_max=4, post_max=4, pre_avg=18, post_avg=18, delta=delta, wait=wait)
    env = np.zeros(n); k = np.exp(-1 / (tau * fps))
    amp = np.zeros(n); amp[pk] = np.clip(fx[pk], 0, 1.0)
    v = 0.0
    for i in range(n):
        v = max(v * k, amp[i]); env[i] = v
    return env, pk

rms = librosa.feature.rms(y=y, frame_length=2048, hop_length=hop)[0][:n] + 1e-9
loud = smooth(norm_db(rms ** 2, 2, 99.8), 0.03, 0.25)
low = smooth(norm_db(band(25, 140)), 0.02, 0.18)
mid = smooth(norm_db(band(140, 2200)), 0.03, 0.22)
high = smooth(norm_db(band(2200, 11000)), 0.02, 0.15)
kick, kpk = pulses(flux(band(30, 120)), 0.12, 10, 0.16)
snare, spk = pulses(flux(band(1800, 8000)), 0.10, 8, 0.12)
onset = librosa.onset.onset_strength(y=y, sr=sr, hop_length=hop)[:n]
onset = smooth(np.clip(onset / np.percentile(onset, 99.5), 0, 1), 0.01, 0.12)
energy = smooth(norm_db(rms ** 2, 2, 99.8), 1.2, 1.8)        # slow section intensity

# 32 log bands spectrum at 30 fps
hop2 = 800
M = librosa.feature.melspectrogram(y=y, sr=sr, n_fft=2048, hop_length=hop2, n_mels=32, fmin=40, fmax=11000, power=2.0)
Md = 10 * np.log10(M + 1e-12)
lo_, hi_ = np.percentile(Md, 5, axis=1, keepdims=True), np.percentile(Md, 99.6, axis=1, keepdims=True)
spec = np.clip((Md - lo_) / (hi_ - lo_), 0, 1)
g = np.clip((Md - np.percentile(Md, 5)) / (np.percentile(Md, 99.8) - np.percentile(Md, 5)), 0, 1)
spec = 0.55 * spec + 0.45 * g
spec = spec.T  # frames x bands

def b64(a):
    return base64.b64encode(np.round(np.clip(a, 0, 1) * 255).astype(np.uint8).tobytes()).decode()

P = 60 / 111.995
data = dict(
    fps=60, n=int(n), duration=round(dur, 4),
    bpm=111.995, period=P, beat0=0.095, bar0=0.095 + 2 * P,
    ch={k: b64(v) for k, v in dict(loud=loud, low=low, mid=mid, high=high, kick=kick, snare=snare, onset=onset, energy=energy).items()},
    specFps=sr / hop2, specBands=32, specN=int(spec.shape[0]), spec=b64(spec.reshape(-1)),
    kicks=[round(float(i / fps), 3) for i in kpk],
)
with open(OUT, 'w') as f:
    f.write('/* One Last Kiss MV - precomputed audio features (generated by tools/analyze_audio.py) */\n')
    f.write('window.OLK_AUDIO=' + json.dumps(data, separators=(',', ':')) + ';\n')
print('frames', n, 'kicks', len(kpk), 'snares', len(spk), 'bytes', len(open(OUT).read()))
for t0 in [10, 40, 60, 100, 140, 160, 200, 230]:
    i = int(t0 * fps); print(t0, 'loud %.2f low %.2f mid %.2f high %.2f energy %.2f' % (loud[i], low[i], mid[i], high[i], energy[i]))
